### ISSUE TITLE
Make margin names more friendly

### ISSUE THREAD

**Issue by abunsen** [repaygithub/cactus#164]
Would be great to have more user friendly props for margin names like `verticalMargin` and `horizontalMargin` instead of `my` and `mx`.

**Comment by JamesNimlos** [comment]
This is interesting, we'd have to extend the built-in margin utility from Styled System. It does also include `marginX` and `marginY`, but I'm guessing that doesn't really provide the improved readability you're looking for.

**Comment by abunsen** [comment]
Yeah you right.
